### PR TITLE
#168 do not show http(s) prefix but add it when missing at launch

### LINKED ISSUE #168: Website not clickable
**Describe the bug**
In some cases, the website in the contact details can not be clicked.

**To Reproduce**
1. Go to 'Musik Hofmann' using the search
2. Click on 'www.musik-hofmann.de'
4. Nothing happens 😞 

**Expected behavior**
The browser should open and display the website of Musik Hofmann.

**Screenshots**

https://user-images.githubusercontent.com/13063245/103995717-235bd880-5199-11eb-850f-c35bd3d7433f.mp4

### PR DESCRIPTION
**Pull request by elKei24**
Closes #168

### CODE REVIEW

**Review by PaulaWi — APPROVED** [review]

File: frontend/lib/util/sanitize_contact_details.dart [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+String prepareWebsiteUrlForDisplay(String website) => website
+    .trim()
+    .replaceAll(_httpRegex, "");
+
+String prepareWebsiteUrlForLaunch(String website) {
+  var trimmed = website.trim();
+  if (_httpRegex.hasMatch(trimmed)) {
+    return trimmed;
+  } else {
+    return "https://$trimmed";
```
Comment (maxammann) [inline frontend/lib/util/sanitize_contact_details.dart:17]: Or should we go with http? I think the security aspect is not that important here.

**Review by maxammann — APPROVED** [review]

File: frontend/lib/util/sanitize_contact_details.dart (hunk 1 above)
Comment (Schedulaar) [reply frontend/lib/util/sanitize_contact_details.dart:17]: I don't really have a strong opinion here. Unfortunately, I believe that there are still a lot of websites out there with only http, hence I'd suggest to actually do `http`... Good servers will redirect to https anyways

**Review by Schedulaar — APPROVED** [review]
