### PR TITLE
#289 fix crash with invalid region IDs

### LINKED ISSUE #289: Region Id mismatch can prevent identification tab from rendering
https://github.com/ehrenamtskarte/ehrenamtskarte/blob/5482c6cdd9fd84a4e0fa6951dedf8a015687a5e8/frontend/lib/identification/card_detail_view.dart#L33-L38

From the documentation of `firstWhere`:

> Returns the first element that satisfies the given predicate test.
> Iterates through elements and returns the first to satisfy test.
> If no element satisfies test, the result of invoking the orElse function is returned. If orElse is omitted, it defaults to throwing a StateError.

So if a region id is not in the returned list the exception prevents the page from rendering.

A possible fix could be:
```dart
          var region = result.hasException || result.isLoading
              ? null
              : getRegions.parse(result.data).regions.firstWhere(
                  (element) => element.id == cardDetails.regionId,
                  orElse: () => null);
```

### PR DESCRIPTION
**Pull request by elKei24**
Closes #289

### CODE REVIEW

File: frontend/lib/verification/view/verification_result.dart [hunk 1]
```diff
@@ -52,13 +52,18 @@ class VerificationResult extends StatelessWidget {
...
-            var exception = verifyResult.hasException
-                ? verifyResult.exception.toString()
-                : regionsResult.exception.toString();
+          if (regionsResult.hasException) {
+            debugPrint(regionsResult.exception.toString());
             return NegativeVerificationResult(
-                VerificationError(exception, "verifyRequestError"));
+                VerificationError("Fehler bei der Kommunikation mit dem "
+                    "Server.", "queryRegionsError"));
           }
```
Comment (elKei24) [inline frontend/lib/verification/view/verification_result.dart:67]: Has nothing to do with the bug, but I think we should not just forward potentially cryptic exception messages to the user but instead log them.

File: frontend/lib/verification/view/result_card/positive_verification_result.dart [hunk 2]
```diff
@@ -26,8 +26,9 @@ class PositiveVerificationResult extends StatelessWidget {
         child: Column(
           children: [
             Text("Name: ${cardDetails.fullName}"),
-            Text("Ablaufdatum: $expirationDateString"),
-            Text("Landkreis: ${region.prefix} ${region.name}"),
+            Text("Gültig bis: $expirationDateString"),
+            if (region != null)
+              Text("Ausgestellt von: ${region.prefix} ${region.name}"),
```
Comment (Schedulaar) [inline frontend/lib/verification/view/result_card/positive_verification_result.dart:31]: Oh this absent null-safety :cry:

**Review by Schedulaar — APPROVED** [review]

**Review by RoAnBu — APPROVED** [review]
