### PR TITLE
#374 check if location permission is granted in intro slides

### LINKED ISSUE #374: Intro slide shows permission button also if already permitted
**Describe the bug**
After upgrading from the old app, the button to allow location access does not do anything if the permission has been granted for the old app.

**To Reproduce**
1. Have the old app installed
2. Upgrade to the new one
3. Go to the last intro slide
4. Tap the button to permit location access

**Expected behavior**
A permission dialogue should be shown.

**Screenshots**
Screenshot_2021-08-28-18-18-48-19_ab1359306de43320f9557c797b1c4be5

https://user-images.githubusercontent.com/13063245/131224362-6655b2af-3269-4429-b8a6-d0d4f2898e54.mp4

### PR DESCRIPTION
**Pull request by RoAnBu**
previously button was static and always asking for location permission although permission was already given in a previous version of the app.
Screenshot_1630844532

closes #374

### CODE REVIEW

File: frontend/lib/intro_slides/location_request_button.dart [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+    checkQuietIfLocationIsEnabled().then(_setInitialLocationStatus);
+  }
+
+  void _setInitialLocationStatus(bool isLocationEnabled) {
+    setState(() {
+      if (isLocationEnabled) {
+        _locationStatus = _LocationStatus.approved;
+      } else {
+        _locationStatus = _LocationStatus.notApproved;
+      }
```
Comment (elKei24) [inline frontend/lib/intro_slides/location_request_button.dart:25]:
```suggestion
      _locationStatus = isLocationEnabled ? _LocationStatus.approved : _LocationStatus.notApproved;
```

File: frontend/lib/intro_slides/location_request_button.dart [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+        return ElevatedButton(
+          onPressed: null,
+          child: Text("Standort ist nicht freigegeben."),
+        );
+        break;
+      case _LocationStatus.error:
+        return Text("Ein unerwarteter Fehler ist aufgetreten.");
+        break;
+    }
+    return Text("Ein unerwarteter Fehler ist aufgetreten.");
```
Comment (elKei24) [inline frontend/lib/intro_slides/location_request_button.dart:73]: We might want to avoid the duplication so that for example the style can be adjusted in a single place.
```suggestion
      default:
        return Text("Ein unerwarteter Fehler ist aufgetreten.");
        break;
    }
```

File: frontend/lib/location/determine_position.dart [hunk 3]
```diff
@@ -82,6 +82,31 @@ Future<bool> canDetermineLocation({BuildContext userInteractContext}) async {
...
+        isLocationEnabled = false;
+        break;
+      case LocationPermission.whileInUse:
+        isLocationEnabled = true;
+        break;
+      case LocationPermission.always:
+        isLocationEnabled = true;
+        break;
+    }
+    return isLocationEnabled;
```
Comment (elKei24) [inline frontend/lib/location/determine_position.dart:103]:
```suggestion
    switch (locationPermission) {
      case LocationPermission.denied:
        return false;
      case LocationPermission.deniedForever:
        return false;
      case LocationPermission.whileInUse:
        return true;
      case LocationPermission.always:
        return true;
      default:
        return false;
    }
```

**Review by elKei24 — APPROVED** [review]
Did not test it, but the screenshot and code look promising. 😃
I only have three small suggestions for simplifying the code.

**Review by Schedulaar — APPROVED** [review]
