### PR TITLE
#110: Decode html entities

### LINKED ISSUE #110: Replace HTML entities with proper characterrs
**Describe the bug**
The html entities are not escaped properly

**To Reproduce**
1. Look for Naturkundemuseum Augsburg

**Expected behavior**
A € symbol should be shown

**Screenshots**
photo5409068863712243745

### PR DESCRIPTION
**Pull request by Schedulaar**
Closes #110

### CODE REVIEW

**Review by elKei24 — APPROVED** [review]

**Review by RoAnBu — APPROVED** [review]

File: backend/src/main/kotlin/xyz/elitese/ehrenamtskarte/importer/general/ImportToDatabase.kt [hunk 1]
```diff
@@ -12,14 +13,23 @@ object ImportToDatabase {
...
+            .getResource("/freinet_import/categories.json").readText()
         val categories = Klaxon().parseArray<Category>(categoriesJson)!!
 
         transaction {
             categories.forEach { CategoryEntity.new(it.id) { name = it.name } }
         }
     }
 
+    private fun decodeSpecialCharacters(text: String): String {
+        // We often get a double encoded string, i.e. &amp;amp;
```
Comment (maxammann) [inline backend/src/main/kotlin/xyz/elitese/ehrenamtskarte/importer/general/ImportToDatabase.kt:25]: lol :D
